### ISSUE TITLE
Error ubuntu 22.04 npm run server host port number

### ISSUE THREAD

**Issue by jackpxyz** [aleixrodriala/wa-tunnel#19]
/home/ubuntu/wa-tunnel/node_modules/on-exit-leak-free/index.js:11
const registry = new FinalizationRegistry(clear)
                 ^

ReferenceError: FinalizationRegistry is not defined
    at Object.<anonymous> (/home/ubuntu/wa-tunnel/node_modules/on-exit-leak-free/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/wa-tunnel/node_modules/pino/lib/tools.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by Lyton505** [comment]
I am also getting this error on Pop! Os

**Comment by Lyton505** [comment]
fixed by updating node to a higher version. I installed v16.20.0
